Kevin Yu
CSE 15L Lab 2
1/30/23

> Part 1









> Part 2

The code I am choosing to work with is the code with testReversed2:
The failure inducing code for the program is: 
```
public void testReverse2() {
int input1 = {1,2,3,4,5}
assertArrayEquals(new int[]{5,4,3,2,1, ArrayExamples.reversed(input1)}
```

The code that runs without failure is:
```
public void testReverse2() {
int input1 = {1,2,3,4,5}
assertArrayEquals(new int[]{5,4,3,2,1, ArrayExamples.reversed(input1)}
```

The symptom upon running the tests is:




